= I liked it so much I bought the company
Keith Wallace
v1.0, 2005-10-03
:title: I liked it so much I bought the company
:tags: [opinion]
ifdef::backend-html5[]
:in-between-width: width='85%'
:half-width: width='50%'
:half-size:
:thumbnail: width='60'
endif::[]

When I was growing up one advertisement spoke to me more than the average sale. Not so much for the style or content - more the underlying message. It was truly American - it basked in the wonders of the American Dream.

The company was Remington. The man Victor Kiam.

The message: "`I liked it so much I bought the company`".

I have to admit, I have not bought Remington Products or even Lunatech Research. What I have bought is something I believe in. Something hot and something I use, something I believe we all will one day, but more of that next time…

It got me thinking. Belief is the most important thing one can have in business. Without it, everything else becomes that little bit harder. Marketing materials, over played. Clients harder to convince. The bank manager, always allowed to win that round. In other words, business becomes more a chore rather than an enchantment.

>Is belief back? Did it ever go away? Well the truth is there has always been a modicum backing-up business. But it does seem the bubble time of pure hunches is over.

Belief now needs to be backed up with something else: Qualified Risk. People look to hard black figures first, make their call and then hit the market with belief in their hearts and dollar signs in their eyes. That is and was true for good examples in the old economy, new economy and the economy of now.

Risk is indeed all important. That old adage, you have to speculate to accumulate. How true. But what can one risk? Money comes to mind. Effort certainly. But we should also consider reputation, network and more importantly deal flow. Ideas, I hear you proffer? Our belief, anyone can have them, its the action that matters. Action that leads toward success.

As I invest personally and with Lunatech these things often come to mind. Sometimes its good to set them down.

Ideas without effort are worthless.

Belief, action and risk, the hallmarks of a good entrepreneur.

Common sense, it’s true, but follow it and we can all be like Victor Kiam.

Something worthwhile, I hope you'll agree.
