= The hype is back baby - and this time its for real!
Keith Wallace
v1.0, 2005-09-01
:title: The hype is back baby - and this time its for real!
:tags: [opinion]
ifdef::backend-html5[]
:in-between-width: width='85%'
:half-width: width='50%'
:half-size:
:thumbnail: width='60'
endif::[]

I have to admit a slight dislike for Amsterdam - wrong of me I know as a foreigner in this fine Kingdom - but true all the same.  What is it I don't like about the city I hear you murmuring, somewhat impassively?  Well,  I could say its the transient nature of its international community.  I do have an issue with that to be sure.  But the pinnacle of truth is harder to spot.  I guess I just like the civilisation of the courtly city of the Hague and the work-happy attitudes of Europe's biggest port.  It leaves little love for the city of marketeers and social benefits. However, yesterday I experienced one of those moments that makes me comprehend the enjoyment many derive from this liberal paradise.

It started as any other trip on the Dutch railways.  I had to walk through the rubble of Rotterdam CS, past the army of smokers hanging loosely at its doors.  I strolled purposefully towards my train, which was of course delayed.  Only twenty minutes.  I'd made provision for that, anyone using the train normally does.

>An hour or so later I arrived.  Amsterdam CS in all of its 'building-in-progress' glory.  I took a breath, dodged the hawkers and made my way to the Post CS building.  I was heady, moreover, I was heading to a launch.  A real product launch and press conference.  I had vague recollections of attending them in the hype years, and it was a nice time to remember.

Sixty or so people in an immense space, the former basketball court of the PTT, now a trendy restaurant. A few known faces.  A little networking then the settling down to hear Minister for Economic Affairs Brinkhorst accept his SimPC, a network computer for the older generation.  He was gracious.  The explanation of the product enlightening.  The questions not entirely staged.  All-in-all there was a buzz.

Then it happened.  An invitation that carried me back to the bubble years.

"`We'd like you all to join us in a glass of champagne to celebrate the launch.`"

Did I resist, I must admit I did not.  A chilled glass of Veuve Cliquot was thrust my way by https://www.linkedin.com/in/borisvvz[Boris] (VvS) and we verily toasted the health of the company.  With the bubbles and the beer that followed it, the networking was electric.  The beer was the indicator.  This company is not a bubble wannabe.  It has its feet firmly on the ground.  A little champagne, however, helped with a real buzz that seems to be building around IT once more.  People are doing business.  And that makes all of us in IT happy indeed.

I raise my glass to http://www.simpc.com/[SimPC] and Rob Rooken.  I almost like Amsterdam now.  Well, I don't dislike it any more.  As an adopted South Hollander, you don't know how difficult that was to say.
