= Who wants to start a company anyways?
Michael Pentowski
v1.0, 2005-12-01
:title: Who wants to start a company anyways?
:tags: [opinion]
ifdef::backend-html5[]
:in-between-width: width='85%'
:half-width: width='50%'
:half-size:
:thumbnail: width='60'
endif::[]

I read a lot of articles with tips for young entrepreneurs, ten steps to a successful company, how to write business plans, etc etc etc.  But I often ponder - Why would anyone in their right mind want to start a company. I mean, really.

++++
<p>I am a founding partner of <a href="http://www.lunatech.com/">Lunatech Research</a>, an IT research and development company. I am an active business mentor, coach, and <a href="http://www.lunatech.com/investments/">investor in early stage startups</a>. I have helped our portfolio companies raise additional rounds of investments. I've hired, I've fired, I've laughed, I've cried. I would find it next to impossible to work for an "employer" ever again. Yet for the life of me, I can't figure out why anyone would want to start their own company.</p>

<p>Are you really an <a href="http://dictionary.reference.com/search?r=2&q=entrepreneur">entrepreneur</a>? Do you have single minded focus to succeed, willing to sacrifice all for your idea and dreams? Coming up with an idea and starting a company are two different animals. There are lots of good inventors, yet the odds are these same gifted inventors are not good entrepreneurs or managers. Can you make a decision, communicate it, and implement on it? Do you take the advice of others on board? Do you think you are qualified to run and manage a startup company? And if successful, can you hand the reins to someone else? How about customers, besides having any, do you actually like them? Customers require attention, support, and are often very demanding. Maybe it is wiser to sell your idea to someone else and let them have the customers. Then you can go off and dream up another idea to peddle.</p>

<p>Let's start with the basics: what is your idea? What has not been done that you are going to do better? Ok, I'll give you a few minutes to think this one over. Have you researched your idea to see how many companies have already introduced a like product or service? So you are most likely playing catchup before you even started. For example, I recently has someone pitch an investment idea which nobody else had implemented... <a href="http://www.google.com/dirhp">a search engine with a directory structure</a>. After long deliberation (50-60 milliseconds)  I decided not to fund this earth shattering concept. Perhaps a missed opportunity but a decision I will have to live with.</p>

<p>Do you like to take holidays? Not any more. (Proper) Entrepreneurs don't go on holidays for the first few years. This may explain why the spirit for startups in Europe is less than in the States, where holidays are somewhat limited to begin with. You can't have your cake an eat it too, being a shareholder is the "reward", having less free time is part of the price you pay. If you are in a relationship, please prepare your other half for the bad news... you will have a mistress that takes up a lot of the time you used to share together. If you succeed, in the medium to long term you will get your free time back. If you succeed that is.</p>

<p>Having employees versus being employed. Ahh.. the thrill of having employees. And the responsibilities it carries. The endless search for the right candidates. The excitement of hiring someone only to find you made a terrible mistake. Now you get to fire them and start the search all over. Being "sick" on company time is fun, having employees sick on your time is costly. The Monday morning brew-flu is great for productivity. Flexible work hours means being able to come in late or leave early,  yet try getting the average employee to work over when you have a pending deadline (which is pressed because the previous weeks they took some very short gun-to-your head holiday time). What you must also consider is how good are you at motivating employees. As a startup, the odds are you will being paying poorly, have no benefits package, have office furniture made from crates and old doors, and expect people to work 50 hours per week. Easier said than done.</p>

<p>The need for investors: Finding investment is a full time occupation. A lucky few entrepeneurs can find investors to fund them. Most can't and then abandon the project and move on (most likely back in the safe world of employer/employee). A small percentage, the real entrepeneurs, try to figure out a creative way to create cashflow with the resources and opportunities at hand. And how about those banks? Banks are adverse to risk, which in the bigger scheme of things I suppose is good. As a startup, banks are not your friend. In the Netherlands, bankers themselves have a saying - "Banks will give you an umbrella only when the sun is shining". A bit of self-deprecating humour, but I think it pretty well sums things up.</p>

<p>So we have briefly discussed the entrepreneur, the idea, the employer/employee relationship, investment, and lack of free time. If this does not scare you off, then perhaps you may really want to consider starting that company afterall. Good luck, be careful.</p>
++++