= Support for generics in XDoclet 1.2/1.3 anyone?
Pepite
v1.0, 2005-12-05
:title: Support for generics in XDoclet 1.2/1.3 anyone?
:tags: [java]

We moved to the latest Java 1.5, and if there is something we love about this new version, it is certainly the use of generics. However, http://xdoclet.sourceforge.net/xdoclet/[XDoclet] support for generics is non-existent. The XDoclet team, did release a new version that allows you to generate classes containing generics, but there is no generics support. So I fixed it.

++++
<p>For example, the following method defined in the EJB bean implementation:</p>

<pre>
public Collection&lt;Number&gt; ejbFindByCommonKey(Number key)
    throws FinderException
</pre>

<p>should result in a the following generated method in the local Home interface:</p>

<pre>
public Collection&lt;myEJBean&gt; findByCommonKey(Number key)
    throws FinderException
</pre>

<p>Currently, Xdoclet completely ignores the generics and the resulted method is:</p>

<pre>
public Collection findByCommonKey(Number key)
    throws FinderException
</pre>

<p>Which, of course, is not exactly what we want to see as we switched to Java 1.5. I therefore tried to 'fix' this bad behavior. After downloading the source code of XDoclet and XJavaDoc, compiling the source code and changing the JavaCC parser, I had it memorize the generic annotation and then it was fairly easy to modify the EJB module to have the desired effect.</p>

<strong>Update (6 December 2005)</strong>: Yesterday evening, I decided to improve the support for CMP. The relationships between the EJB CMP beans are now better handled. For example, if you have the following relationship in your EJB:

<pre>
/**
 * Getter for CMR Relationship
 *
 * @ejb.interface-method
 *   view-type="local"
 * @ejb.relation
 *   name = "myEJB-myOtherEJBs"
 *   role-name = "myEJB"
 *   target-role-name = "myOtherEJB"
 */
public abstract Collection&lt;myOtherEJB&gt; getOtherEJBs();

/**
 * Setter for CMR Relationship
 *
 * @ejb.interface-method
 *   view-type = "local"
 */
public abstract void setOtherEJBs(Collection&lt;myOtherEJB&gt; value);
</pre>


<p>It will now generate the following in the local interface:</p>

<pre>
/**
 * Getter for CMR Relationship
 */
public Collection&lt;myOtherEJB&gt; getOtherEJBs( );

/**
 * Setter for CMR Relationship
 */
public void setOtherEJBs(Collection&lt;myOtherEJB&gt; value);
</pre>

<p>and update the Deployment Descriptor (ejb-jar.xml) in the appropriate relationship element with:</p>

<pre>
&lt;ejb-relationship-role&gt;
  &lt;ejb-relationship-role-name&gt;myEJB&lt;/ejb-relationship-role-name&gt;
  &lt;multiplicity&gt;One&lt;/multiplicity&gt;
  &lt;relationship-role-source&gt;
    &lt;ejb-name&gt;MyEJB&lt;/ejb-name&gt;
  &lt;/relationship-role-source&gt;
  &lt;cmr-field&gt;
    &lt;cmr-field-name&gt;myOtherEJB&lt;/cmr-field-name&gt;
    &lt;cmr-field-type&gt;java.util.Collection&lt;/cmr-field-type&gt;
  &lt;/cmr-field&gt;
&lt;/ejb-relationship-role&gt;
</pre>

<p><strong>Update (8 December 2005)</strong>: It seems that I forgot a file in the patch file (the MethodTagsHandler class). I have therefore updated it with the diff for the MethodTagsHandler class. Sorry for the trouble.</p>

<p><strong>Update (16 December 2005)</strong>: I have made (yet another) mistake putting the binary files in the repository. I have updated with the right binary files (xdoclet-1.3-16122005-lunatech.jar and xdoclet-ejb-module-1.3-16122005-lunatech.jar). Sorry again for the mistake.</p>


<p><strong>Update (19 December 2005)</strong>: I have updated the xjavadoc library to support fully qualified name on generics. For example:</p>

<pre>
public class MyBean {

    /**
     * @ejb.interface-method view-type="remote"
     */
     Set&lt;CustomType&gt; bar() {
        /* ... */
     }
}
</pre>

<p>now generates:</p>

<pre>
java.util.Set&lt;foo.bar.CustomType&gt; bar();
</pre>

<p>in the local and remote interface.</p>

<p><strong>Update (8 January 2006)</strong>: The permission section in the ejb-jar.xml was not correct. It did not strip the generics part, resulting in an invalid xml file. It is now solved. New versions are available at the usual place.</p>

<p><strong>Update (29 January 2006)</strong>: Fixed a bug where Map&lt;String, String[]&gt; resulted in  Map&lt;String, null&gt; . It now generates  Map&lt;java.land.String, java.lang.String[]&gt;</p>

<p><strong>The source directory is not up to date. I will try to generate diff files as soon as possible. If you required the source files don't hesitate to contact me.</strong></p>

<p>Here are the source code changes, and the compiled version of <code>xjavadoc</code> and the <code>ejb modules</code> if you want to use it right away without recompiling everything.</p>

<p>Source File and diff changes (using  <code>diff -Naur xdoclet-cvs xdoclet-lunatech</code> against the cvs head branch of xdoclet and xjavadoc) are located in the following directory:</p>

<ul>
	<li>xjavadoc: <a href="http://www1.lunatech.com/~nicolas/xjavadoc/src/">source directory</a></li>
       <li>xdoclet: <a href="http://www1.lunatech.com/~nicolas/xdoclet/src/">source directory</a></li>
</ul>

<p>Binary Files:</p>

<ul>
	<li>XJavaDoc: <a href="http://www1.lunatech.com/~nicolas/xjavadoc/lib/xjavadoc-1.5-29012006-lunatech.jar"> xjavadoc-1.5-29012006-lunatech.jar</a></li>
        <li>EJB Modules: <a href="http://www1.lunatech.com/~nicolas/xdoclet/lib/">xdoclet modules</a></li>
</ul>

<p>If you are using Eclipse and Jboss-ide, simply copy the files above into &lt;your Eclipse directory&gt;/plugins/org.jboss.ide.eclipse.xdoclet.core_&lt;version&gt;/. Remove the previous version of the library (<code>xjavadoc.jar</code> and <code>xdoclet-ejb-module-1.2.jar</code>).</p>

<p>You will need this library as well  <a href="http://sourceforge.net/project/showfiles.php?group_id=16035">DOM4J 1.6.1</a>.</p>

<p>Please remember that this version of XDoclet will only work with JDK1.5. The EJB module and the XDoclet core module have been changed, so feel free to change the other modules to suit your needs.</p>

++++