= How to use bullet lists
hilton
v1.0, 2006-09-11
:title: How to use bullet lists
:tags: [writing]

Bullet http://en.wikipedia.org/wiki/List_%28composition%29[lists] are much used and abused, especially in business and technical writing. However, if you follow some simple rules of thumb, bullet lists can improve your writing's readability and reduce duplication, instead of being a poor substitute for well-formed prose.

++++
<h2>Readability and reduced duplication</h2>

<p>Improved readability comes from making it easier to see the structure, scan and skip past the list, and to compare list items. Try picturing pages from a novel: each page is a block of text, structured by paragraphs. Against this backdrop of letters and punctuation, a vertical column of bullets stands out clearly as a recognisable section of the text, with a clear start and end. This is why it is easy to glance at the list as a whole or skip past it to the text that follows.</p>

<p>Within a bullet list, the bullets stand out as markers for the start of each consecutive bullet item. This enables scanning the first few words of each list item and skipping to the next list item, whose start is clearly marked by the bullet at the start. At the same time, the layout of a vertical list aligns list items, which is what enables comparison, as you glance back and forth between items in the same list.</p>

<p>Reduced duplication comes from factoring out the common part of a list into a lead-in phrase. Consider the following text.</p>

<blockquote>
<p>This specification is split into several sections. The first section specifies the system's user-interface. The next section describes the system's external interfaces. The section after that specifies the system's data model.</p>
</blockquote>

<p>The following refactored version says the same thing more clearly in half the number of words.</p>

<blockquote>
<p>This specification is split into three sections, which specify the system's:</p>
<ul>
<li>user-interface</li>
<li>external interfaces</li>
<li>data model.</li>
</ul>
</blockquote>


<h2>A bullet list is a list</h2>

<p>A bullet list is a list. Surprisingly, people often use lists as if they did not realise this. Most of what follows is about recognising a bullet list's list-nature. What this means is that lists make sense when you use them to structure the text's meaning, rather than just to control their layout.</p>

<p>When using bullet lists, we can learn from programming languages, which are more structured than natural languages. For example, with Java Collections, you are asking for trouble if you mix different kinds of things in the same list. If the list items are too different then the list suggests a relationship between the items that is not there, and you would actually be better off with a sequence of paragraphs.</p>

<blockquote>
<p>This example list has mixed classes: each item lacks context, and does not follow from the previous item. This would make it impossible to have a coherent lead-in phrase.</p>

<ul>
<li>This list is an example of the problem</li>
<li>Consider the lead-in phrase</li>
<li>Context</li>
<li>What are the previous two items about?</li>
</ul>

<p>This example is a consistent list - i.e. it does not have mixed classes. This is more readable because each item is the same kind of thing - an advantage of consistent lists.</p>

<ul>
<li>Increased readability and flow</li>
<li>Makes the list easier to understand</li>
<li>Makes it possible to use a lead-in phrase</li>
<li>Makes it possible to compare items</li>
</ul>
</blockquote>

<p>As with Java generics, you also improve readability if you explicitly state what the list is a list of. To do this, use a lead-in phrase or a heading.</p>


<h2>Bullet list syntax</h2>

<p>As with typefaces, the best way to ensure consistency is to limit the amount of variation to what you need. For bullet lists, you have all you need if you stick to two (arbitrarily-named) types with different syntax.</p>

<p>Type 1 lists have:</p>

<ul>
<li>the same structure as a single sentence</li>
<li>a lead-in phrase</li>
<li>list items starting in lower-case</li>
<li>a full-stop after the last item.</li>
</ul>

<p>Type 2 lists have a different syntax, as follows.</p>

<ul>
<li>The structure is the same as for a sequence of sentences.</li>
<li>The lead-in phrase, if used, is a whole sentence.</li>
<li>Each item is a complete sentence in sentence case.</li>
</ul>


<h2>Alternative syntax</h2>

<p>The syntax guide above is just one particular style. There is no single correct way to write lists, and other styles are in use, some better than others. A newspaper's style guide, for example, might specify a variation that also makes sense. You may see the following variations.</p>

<ul>
<li>Some people use a colon-dash (:-) at the end of the lead in phrase in Type 1 lists. This is horrible bogus punctuation, and should be avoided.</li>
<li>Some house styles require a comma at the end of each bullet item in Type 1 lists, as with a normal comma separated list. This does not really do any harm, but the bullets make the commas redundant.</li>
<li>It often makes sense to omit the full-stop at the end of single-sentence list items in Type 2 lists, when the list stands alone, without surrounding paragraphs. This is most natural on a presentation slide.</li>
<li>Presentations often contain Random Capitalisation, which is also bizarre and inconsistent. Avoid.</li>
</ul>


<h2>When to use a bullet list</h2>

<p>Bullet lists are useful for removing duplication in a sequence of sentences, if you can factor out the common part into the lead-in phrase. This is especially useful when writing for the web, when you want lists of hyperlinks.</p>

<p>Bullet lists are also useful for improving readability by making the text's structure more visible than it would be in plain prose. For example, with a bullet list it is easier to skip to the end of the list or compare list items.</p>

<p>This is why bullet lists are most appropriate in text that is going to be scanned as well as read sentence-by-sentence. This includes most non-fiction and probably all technical writing. Conversely, bullet lists are not useful or appropriate for text that is intended to be read linearly, such as a novel.</p>


<h2>Numbered lists</h2>

<p>Numbered lists, which have the same syntax as bullet lists, are useful when:</p>

<ul>
<li>you want to emphasise that the list's order is significant
</li><li>there are lots of list items, because the list size makes it difficult to pick out a list item by position
</li><li>you want to refer to particular list items.
</li></ul>


<h2>Bullet lists in presentations</h2>

<p>Bullet lists are a natural choice for presentations, because of the audience's need to quickly scan the text while the presenter is speaking. However, after so many years of presentation software defaulting to bullet list slide layouts, bullet lists so often signal a bad presentation, and easily invoke a special kind of numbness in the audience, not dissimilar to sleep.</p>

<p>At the very least, make sure your bullet lists are well-formed. Beyond that, try to go <a href="http://www.beyondbullets.com/">Beyond Bullets</a> and seek <a href="http://www.presentationzen.com/">Presentation Zen</a>.</p>

++++