= The Urban Country Club
Michael Pentowski
v1.0, 2006-08-17
:title: The Urban Country Club
:tags: [fun]


I'd like to tell you about the http://www.urbancountryclub.nl/[Urban Country Club], but I am not sure if I can. It is an invite only network club in Rotterdam, where members can invite one new member, but only if they don't know them. Or something like that. That said, membership can't be too exclusive as they let me in. Perhaps they needed a token IT company as the rest of the people are very creative, coming from the arts, film, madvertising and the like.

++++
<p>What I dare say about the Urban Country Club formula… take a bunch of influential people who are not from the same circles and meet once every 4-6 weeks, throw some new members to the lions for entertainment factor, imbibe in copious quantities of alcohol, film everything, and voila… you have a recipe for a great networking club. Keep it exclusive, keep it fresh, keep it fun. I hope they introduce a secret handshake soon.</p>

<p>The club interviews all new members. Not for the faint of heart, but if you can stomach around 10 minutes, you can see <a href="http://www.antennetv.nl/read/movie_item_nieuw/id/41708/Titel/ucc-wormshow-3">yours truly stumbling through an interview in Dutch</a>. If this doesn't kill you, there is a second interview (at 3m:45s) in more comfortable surroundings with a drink in hand (speaking English this time). Is it just me, or does everyone hate to hear their own voice?</p>
++++