= Upgrade your JSPs to XML (but not to .jspx)
bartschuller
v1.0, 2006-01-20
:title: Upgrade your JSPs to XML (but not to .jspx)
:tags: [java,web-applications,struts]


Recently we were redesigning the views for a web application. The previous version used JSP files and Struts tiles. In trying to be as standards-compliant as possible, we decided that our pages should generate XHTML and so it made sense to write them as JSP documents, the fancy name for .jspx files.

++++
<p>This then should be a proper JSPX:</p>

<pre><code>
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;jsp:root xmlns:jsp="http://java.sun.com/JSP/Page" version="2.0"
        xmlns="http://www.w3.org/1999/xhtml"&gt;
&lt;jsp:directive.page contentType="application/xhtml+xml; charset=UTF-8"/&gt;
&lt;html&gt;
 &lt;head&gt;
  &lt;title&gt;Entities in jspx files&lt;/title&gt;
 &lt;/head&gt;
 &lt;body&gt;
  &lt;h1&gt;Entities in jspx files: This should be a proper ampersand: &amp;amp;&lt;/h1&gt;
 &lt;/body&gt;
&lt;/html&gt;
&lt;/jsp:root&gt;
</code></pre>

<p>But when you try it out with Firefox, it rightly complains about a lone ampersand appearing. Viewing the source, you notice that it now says: <code>ampersand: &amp;&lt;/h1&gt;</code>.</p>

<p>So it appears that every ampersand used for every entity or character reference needs to be escaped itself. It's hard to describe just how wrong this is, but let me just list a couple of things you can no longer do:</p>

<ul>
	<li>Paste pre-written XHTML into your JSPX</li>
	<li>Use XSLT to transform your own XML into JSPX</li>
	<li>Change a JSP to a JSPX by only changing the first few lines of the file and adding a &lt;jsp:root&gt;</li>
	<li>Tell technical writers: this is just an XML format like any other (DocBook for example). Start your XML editor and start typing</li>
</ul>

<p>Didn't the spec writers notice how wrong this is? They did. From the JSP 2.1 Proposed Final Draft, unchanged from the 2.0 spec:</p>

<blockquote>
<strong>JSP.6.5.1 Generating XML Content Natively</strong>
<p>All JSP 2.0 content is textual, even when using JSP documents to generate
XML content. This is quite acceptable, and even ideal, for some applications, but in
some other applications XML documents are the main data type being manipulated.
For example, the data source may be an XML document repository, perhaps queried
using XQuery, some of the manipulation on this data internal to the JSP page will
use XML concepts (XPath, XSTL operations), and the generated XML document
may be part of some XML pipeline.</p>

<p>In one such application, it is appealing not to transform back and forth
between a stream of characters (text) and a parsed representation of the XML
document. The JSP expert group has explored different approaches on how such
XML-awareness could be added, and a future version of JSP could support this
functionality.</p>
</blockquote>

<p>The rub is in this sentence: <em>This is quite acceptable, and even ideal, for some applications, but in some other applications XML documents are the main data type being manipulated.</em></p>

<p><strong>No, it is not acceptable!</strong></p>

<p>The main, 99% use of JSP(X) technology is producing some form of HTML or XML. The rules aren't any different for HTML as opposed to XML so, crazy as it may sound, our 99% falls into the <em>some other applications</em> category.</p>

<p>There are no other words for it, it has to be said:</p>

<p><strong>JSP documents are broken as designed.</strong></p>

<p>So, for us, in this project, it's back to plain JSP.</p>

<p>P.S.</p>

<p>If you wonder how we can get away with serving <code>application/xhtml+xml</code> content without complaints from Internet Explorer users, that's food for a separate article.</p>

<p>P.P.S.</p>

<p>After writing this article I started wondering how Sun's Java Server Faces copes with this problem. It turns out that yes, it is a problem for JSF files as well. See <a href="http://blogs.sun.com/roller/page/tor?entry=mixing_jsf_and_html">this blog entry</a> for the gory details.</p>
++++