= Struts Action Mappings - configuring web application URLs
hilton
v1.0, 2006-01-23
:title:  Struts Action Mappings - configuring web application URLs
:tags: [java,web-applications,struts]



In the article on https://blog.lunatech.com/2005-07-29-struts-urls[Struts URLs for Perfectionists] I described one way of defining the action mappings for a Struts web application. One of Struts' double-edged swords is that there are several ways to do this, each with its pros and cons. This article considers a few alternatives.

++++
<h3>Individual action mappings in <code>struts-config.xml</code></h3>

<p><em>Approach</em>: manually add an action element to <code>struts-config.xml</code> for each Action mapping.</p>

<p><em>Pros</em>: simplicity, and the most examples online.</p>

<p><em>Cons</em>: effort to maintain <code>struts-config.xml</code>.</p>

<pre>&lt;action path='/search' type='myapp.web.SearchAction' name='SearchForm'&gt;
	&lt;forward name='search' path='/WEB-INF/jsp/Search.jspx' redirect='false'/&gt;
&lt;/action&gt;</pre>

<p>This approach is most straightforward, and is a good way to start. However, if the number of actions continually grows it becomes a hassle to keep <code>struts-config.xml</code> in sync.</p>

<p>One thing that certainly helps is a strict convention for Action class names based on the URL path, so you do not have look at the configuration each time you want to look at a URL's action, or vice versa.</p>

<p>It also helps to keep the action mappings sorted by path, to make it easier to browse and to avoid duplicate entries.</p>

<h3>Use <code>DispatchAction</code> to group related actions</h3>

<p><em>Approach</em>: combine related actions as separate methods in a <code>DispatchAction</code> subclass</p>

<p><em>Pros</em>: simplified struts-config.xml with fewer entries</p>

<p><em>Cons</em>: unpredictable action method names</p>

<pre>&lt;action path='/customer' type='myapp.web.CustomerDispatchAction'
name='SearchForm' parameter='method'&gt;
&lt;forward name='view' path='/WEB-INF/jsp/CustomerView.jspx' redirect='false'/&gt;
&lt;forward name='edit' path='/WEB-INF/jsp/CustomerEdit.jspx' redirect='false'/&gt;
&lt;forward name='delete' path='/WEB-INF/jsp/CustomerDelete.jspx' redirect='false'/&gt;
&lt;/action&gt;</pre>

<p><code>DispatchAction</code> was the first mechanism Struts provided for simplifying action mappings. It certainly makes sense for related URLs, such as /customer/view, /customer/edit, /customer/delete. Actions group naturally when they share an <code>ActionForm</code>, since each <code>DispatchAction</code> class is associated with one <code>ActionForm</code> in a single action mapping. However, it is less obvious how to group actions that do not use a form.</p>

<p>A harder problem comes when naming <code>DispatchAction</code> methods. It is useful to have a strict convention that simplifies the application's URL API, so there is less to remember. For example, if you group actions by domain type then you may have a <code>CustomerDispatchAction</code> and a <code>ProductDispatchAction</code> each with <code>view</code>, <code>edit</code> and <code>delete</code> methods. The first problem is that not every <code>DispatchAction</code> will use all of the possible method names, so you have to remember whether a URL like <code>/product?method=delete</code> is valid. The second problem is that some actions are difficult to fit into this method name scheme, which makes consistency hard. These are relatively minor, though.</p>

<h3>Wildcard  action mappings in <code>struts-config.xml</code></h3>

<p><em>Approach</em>: reduce the number of action mappings by using wildcards to define generic mappings</p>

<p><em>Pros</em>: fewer action mappings and a strict mapping from URLs</p>

<p><em>Cons</em>: wrong case in class names or upper-case in URLs</p>

<pre>	&lt;action path="/*/*" type="com.example.web.{1}{2}Action"/&gt;</pre>

<p>A good way of avoiding the need to update <code>struts-config.xml</code> every time you add a new page is to add an action mapping with wildcards that you can use for all of your pages, as described in <a href="/2005-07-29-struts-urls">Struts URLs for Perfectionists</a>. This works pretty well, and when I tried this it turned out to be useful for just about all of the pages - there were no exceptions where I could not use the generic action mapping.</p>

<p>The huge disadvantage came when I realised that I could not have both lower-case URLs and camel-case action class names. With the example above, the URL <code>/customer/edit</code> would require a class called <code>customereditAction</code> instead of <code>CustomerEditAction</code>, which is almost as ugly as upper-case letters in the URL.</p>


<h3>XDoclet definitions in Action classes</h3>

<p><em>Approach</em>: use XDoclet tags in the action classes to define action mappings, instead of using <code>struts-config.xml</code></p>

<p><em>Pros</em>: flexible definition of URLs (action mapping paths) and actions (classes) in the same place</p>

<p><em>Cons</em>: more complex build, requiring more Ant knowledge; no enforced mapping conventions</p>

<pre>/**
 * @struts.action path="/customer/edit" name="CustomerForm" validate="false"
 * @struts.action-forward name="default" path="/WEB-INF/jsp/CustomerEdit.jspx"
 */
public class CustomerEditAction extends Action</pre>

My current favourite approach is to use XDoclet annotations in the action class itself to specify the action mapping. Once the Ant build script is set-up to generate <code>struts-config.xml</code> you can then use this approach to keep all of the definitions together, without any duplication. The main advantage is that you can do everything here that you can do in the basic method, of defining action mappings manually. However, this also gives you the disadvantage that your naming conventions for the URL, action class, action form and JSP are not automatic or enforced; in the above example I have four opportunities to misspell 'customer'.


<h3>Generating <code>struts-config.xml</code> another way</h3>

<p>One thing that remains unsatisfying about the above Struts-based approaches is that action mappings are not usually a web application's only URL-specific meta-data. For example, you may wish to define a title for each page, to be used in a page  template. It is therefore a shame, perhaps, that Struts does not provide a mechanism for extensible action meta-data. So far, at least, I have not come across an implementation of this idea.</p>

<p>Instead I have simply used a separate XML document containing a series of elements whose IDs match the Struts action mapping paths. It is then straightforward to parse this XML in a JSP page template, using the JSTL XML tag library, in order to fetch meta-data from the element whose ID matches the current URL.</p>

<p>In the end, the whole action mappings issue seems more like an unresolved design decision in Struts than useful flexibility. I would prefer to see a simpler model with a recommended way of mapping URLs to application code, and good support for making this work well. Perhaps it is time to revisit some of the alternatives to Struts that consider simplicity a virtue.</p>
++++