= Eclipse plug-in installation
hilton
v1.0, 2007-03-08
:title: Eclipse plug-in installation
:tags: [java]

We have found it useful to install plug-ins separately from where Eclipse is installed, so you do not lose the plug-ins when you inevitably delete your Eclipse installation to start again, or install a new version. This works better than relying on Eclipse's self-upgrade working, and is simple when you know how. Here's how.

The idea for installing plug-ins is to keep each plug-in in its own
directory tree, separate from the Eclipse installation, and other
plug-ins. In this example, we are using Linux and want to install
plug-ins in `/usr/local/eclipse-plugins` while Eclipse itself is
installed in the `/usr/local/eclipse` directory.

The following instructions are for Eclipse 3.2.

. In Eclipse, select _Help > Software Updates > Find and Install…_.
. On the _Feature Updates_ wizard page, select _Search for new features
to install_ and click _Next_.
. On the _Update sites to visit_ wizard page, click the _New Remote
Site…_ button.
. On the _New Update Site_ dialogue box, enter the plug-in name and
update site URL from this page, above, and click _OK_.
. On the _Update sites to visit_ wizard page, select *only* the update
site you just created, and click _Finish_.
. On the _Search results_ wizard page, select the required features from
the list, and click _Next_.
. On the _Feature licence_ wizard page, select _I accept the terms in
the licence agreement_, and click _Next_.
. On the _Installation_ wizard page, *select all of the features in the
list and click _Change Location..._*.
. Create and select a new sub-folder of `/usr/local/eclipse-sites/` for
the plug-in you are installing.
. On the wizard, click _Finish_ to start downloading.
. On the _Feature verification_ wizard page, click _Install All_ to
install the plug-in.

The crucial step is step 8, where you choose a different plug-in
installation location to the default, which is inside the Eclipse
installation.

