= Benelux JBoss User Group, 2 November 2007
hilton
v1.0, 2007-10-01
:title: Benelux JBoss User Group, 2 November 2007
:tags: [jbug,event]

Since the [first
event](/2007/06/15/benelux-jboss-user-group-8-june-2007-first-photos)
was so much fun, Lunatech Research hosted the second JBoss Benelux User
Group meeting on 2 November 2007, with a presentation by Bruno Georges.

https://blog.lunatech.com/2007-11-11-benelux-jboss-user-group-2-november-2007-photos[Photos
of the event] are now on-line.

*Date:* Friday, 2 November 2007

*Time:* Arrive 1700-1800, presentations start 1800, finish 2000-2100.

*Location:* link:/contact/[Lunatech Research, Rotterdam]

*Programme:* The programme began with a presentation on Open Source SOA
by Bruno Georges, Technical Development Manager, Enterprise Frameworks
at JBoss. This included an ESB Presentation and a demo based on jBPM for
process flow orchestration.

In the second presentation, Peter Hilton and Nicolas Leroux described
Lunatech's practical experience with JBoss Seam. We talked about
strengths and limitations of JBoss Seam 1.2.1.

* Slides: link:../media/2007-10-01-benelux-jboss-user-group-2-november-2007/jbug-2007-11.pdf[Practical experience with JBoss Seam]

*Refreshments:* Beer and pizza.

If you would like us to let you know about the next JBUG event, please
e-mail pedro+jbug3@lunatech.com.
