--- layout: article drupal-format: Full HTML title: "Meeting-avoidance
for developers - Devoxx08 presentation" tags: project-management
meetings author: Peter Hilton summary: "Peter Hilton will be presenting
a [Meeting-avoidance for self-managing
developers](http://www.devoxx.com/display/JV08/Meeting-avoidance+for+self-managing+developers)
presentation at this year's
[Devoxx08](http://www.devoxx.com/display/JV08/Home)
formerly-known-as-JavaPolis conference. See you there!" ---

== Presentation abstract

Many developers are frustrated by time spent in meetings, when they
would rather be coding. These meetings are often project management
activities, such as weekly project status meetings, that have evolved
into a large fixed overhead on software development projects.

This presentation presents ways for developers to reduce meeting time,
and other overhead, with various tools and techniques to reduce the cost
of project management activities.

Another cause of developer frustration is micro-management by a
non-technical project manager who is not part of the development team.
This presentation describes how a development team can self-manage in
order to address this.

_http://hilton.org.uk/about_ph.phtml[Peter Hilton] is a senior software
developer at Lunatech Research._
