= Launching VisibleLogistics, the on-line solution for demanding customers
Michael Pentowski
v1.0, 2008-02-14
:title: Launching VisibleLogistics, the on-line solution for demanding customers
:tags: [ventures]


Launching http://www.visiblelogistics.com/[VisibleLogistics], the
on-line solution for demanding customers. 

== Where is my stuff?

Your customers always want to know where their 'stuff' is. If you have a
small business that ships what it sells, or if you are buying from one,
this happens all the time: once a shipment has left your premises, it is
completely invisible to you or your customers for most of the time. You
are depending on the efficiency and good will of a carrier with whom you
often have no direct communication, should anything go wrong. Meanwhile,
your customer is just as much in the dark as you are. It is hardly
better for the party organising the transport, who has no way to make
sure that the delivery address is correct, that there will be someone to
receive the package, or simply to let someone know that the vehicle is
stuck in a traffic jam.

VisibleLogistics solves this visibility problem. When you are running a
small business, keeping track of orders and shipments is vital but it
can also be very time-consuming. Phone calls, sending e-mail and sending
faxes are all-important for managing communication with suppliers,
transporters and customers. You frequently have to re-enter all of this
information in spreadsheets, to keep records, which duplicates effort
and wastes precious time.

== The ideal tool for small and medium businesses

With http://www.visiblelogistics.com/[VisibleLogistics], smaller
businesses can cut down this time spent on communicating.
VisibleLogistics combines the processes linked to orders, inventory and
communication with the other partners of the supply chain into one
on-line on-demand application. VisibleLogistics monitors order and
shipment status, and automatically sends e-mails to the relevant parties
when important changes are made.

Unlike the track-and-trace systems provided by the express carriers and
large shipping companies, you can use VisibleLogistics to monitor
shipments across different carriers and transport modes. This can be
useful if agents are moving shipments with a variety of different
carriers. VisibleLogistics is indeed used by small forwarders to provide
shipment monitoring and status updates to their customers. It enables
them to provide service levels that match those of their larger
competitors.

The benefits of VisibleLogistics are improved accuracy, round the clock
availability of information for customers and a single view of all order
and shipment activity.

VisibleLogistics is designed to support small businesses by:

* managing orders using an easy to use application controlled through
any standard web browser
* giving buyers and carriers on-line access to information about orders,
status and catalogues
* notifying business partners by e-mail or SMS when orders are created
and when statuses change
* adding comments to orders, communicating with business partners and
vice-versa.

The message to shippers can be summarised as - Sell it, Ship it, See it.

The basic features of VisibleLogistics are free to use and are described
at http://www.visiblelogistics.com/[www.visiblelogistics.com].

For any additional information, please contact:

Ken Lyon

BitLogistics - Sourceree Solutions Ltd

60, Cannon Street

[.locality]#London# [.postal-code]#EC4N 6NP#

__ +44 (0) 207 618 6500

__ +44 (0) 207 618 8001

__ contact-us@bitlogistics.com

__ http://www.bitlogistics.com/[www.bitlogistics.com]
