= Nouvelles technologies de développement - FPI 2008 in Nice
pepite
v1.0, 2008-05-19
:title: Nouvelles technologies de développement - FPI 2008 in Nice
:tags: [java,event]


Last week Stephane Epardaud and Nicolas Leroux,
senior software developers at Lunatech Research, presented \"Nouvelles
technologies de développement en JEE\" at the Forum des Professions
Informatique 2008 in Nice.

The conference was organised by the University of Nice and it was rather
pleasant to discuss with the students and other I.T. professionals.
Thanks again for the invitations.

This is also the start of a new Open Source project that will be used as
a show case for new technologies (JBoss Seam, JPA, EJB 3, Hibernate
Search, etc...). The project is available
http://code.google.com/p/seam-registration-example-app[here]. We will
try to write some nice tutorials and articles about it. More to come on
this web, so keep posted.

In the meantime, you can download the
link:../media/2008-05-19-nouvelles-technologies-de-développement-fpi-2008-nice/presentation-iut-2.pdf[presentation slides] in French (PDF, 0.5
Mb).

You can send your comments nicolas+fip@lunatech.com.
