
= What every web developer must know about URL encoding
FroMage
v1.0, 2009-02-03
:title: What every web developer must know about URL encoding
:tags: [java,web-applications]

This article describes common
misconceptions about *Uniform Resource Locator*
(http://en.wikipedia.org/wiki/URL[URL]) encoding, then attempts to
clarify http://en.wikipedia.org/wiki/Percent-encoding[URL encoding]
for http://en.wikipedia.org/wiki/HTTP[HTTP], before presenting
frequent problems and their solutions. While this article is not
specific to any programming language, we illustrate the problems in
http://en.wikipedia.org/wiki/Java_(programming_language)[Java] and
finish by explaining how to fix URL encoding problems in Java, and in a
web application at several levels." 

[#Tableofcontents]
== Table of contents

* link:#Introduction[Introduction]
** link:#GeneralURLsyntax[General URL syntax]
** link:#HTTPURLsyntax[HTTP URL syntax]
** link:#URLgrammar[URL grammar]
* link:#CommonpitfallsofURLs[Common pitfalls of URLs]
** link:#Whichcharacterencoding%3F[Which character encoding?]
** link:#Thereservedcharactersaredifferentforeachpart[The reserved
characters are different for each part]
** link:#Thereservedcharactersarenotwhatyouthinktheyare[The reserved
characters are not what you think they are]
** link:#AURLcannotbeanalysedafterdecoding[A URL cannot be analysed
after decoding]
** link:#DecodedURLscannotbereencodedtothesameform[Decoded URLs cannot
be reencoded to the same form]
* link:#HandlingURLscorrectlyinJava[Handling URLs correctly in Java]
** link:#Donotuse%7B%7Bjava.net.URLEncoder%7D%7Dor%7B%7Bjava.net.URLDecoder%7D%7DforwholeURLs[Do
not use `java.net.URLEncoder` or `java.net.URLDecoder` for whole URLs]
** link:#DonotconstructURLswithoutencodingeachpart[Do not construct URLs
without encoding each part]
** link:#DonotexpectURI.getPath%28%29[Do not expect URI.getPath() to
give you structured data]
** link:#DonotexpectApacheCommonsHTTPClient%27s%7B%7BURI%7D%7Dclasstogetthisright[Do
not expect Apache Commons HTTPClient's `URI` class to get this right]
* link:#FixingURLencodingateverylevelinawebapplication[Fixing URL
encoding at every level in a web application]
** link:#AlwaysencodeURLsasyoubuildthem[Always encode URLs as you build
them]
** link:#MakesureyourURLrewritefiltersdealwithURLscorrectly[Make sure
your URL-rewrite filters deal with URLs correctly]
** link:#UsingApachemodrewritecorrectly[Using Apache mod-rewrite
correctly]
* link:#Conclusion[Conclusion]

[#Introduction]
== Introduction

There are a number of technologies we use everyday when we browse the
http://en.wikipedia.org/wiki/World_Wide_Web[web]. There is the data
itself (the web pages) obviously, the formatting of this data, the
transport mechanism which allows us to retrieve this data, and there is
the foundation, the root, the thing that makes the web _a web_: links
from one page to the other. These links are URLs.

[#GeneralURLsyntax]
=== General URL syntax

Everyone by now has seen a URL at least once in his life. Take
"http://www.google.com" for instance. This is a URL. A URL is a _Uniform
Resource Locator_ and is really a pointer to a web page (in most cases).
URLs actually have a very well-defined structure since the
http://tools.ietf.org/html/rfc1738[first specification] in 1994.

We can extract detailed information about the "http://www.google.com"
URL:

[cols=",",]
|===
|Part |Data
|Scheme |http
|Host address |www.google.com
|===

If we look at a more complex URL such as
"https://bob:bobby@www.lunatech.com:8080/file;p=1?q=2#third" we can
extract the following information:

[cols=",",]
|===
|Part |Data
|Scheme |https
|User |bob
|Password |bobby
|Host address |www.lunatech.com
|Port |8080
|Path |/file
|Path parameters |p=1
|Query parameters |q=2
|Fragment |third
|===

The _Scheme_ (here _http_ and _https_ (secure HTTP)) define the
structure of the rest of the URL. Most internet
http://www.iana.org/assignments/uri-schemes.html[URL schemes] have a
common first part which indicates the _user_, _password_, _host_ name
and port, followed by a scheme-specific part. This common part deals
with authentication and being able to know where to connect in order to
request data.

[#HTTPURLsyntax]
=== HTTP URL syntax

For HTTP URLs (with the _http_ or _https_ schemes), the scheme-specific
part of the URL defines the _path_ to the data, followed by an optional
_query_ and _fragment_.

The _path_ part consists in a hierarchical view similar to a file system
hierarchy with folders and files. The path starts with a "/" character,
then each folder is separated from one another by a "/" again until we
reach the file. For example "/photos/egypt/cairo/first.jpg" has four
_path segments_: "photos", "egypt", "cairo" and "first.jpg", which can
be extrapolated as: the "first.jpg" file in the "cairo" folder, which is
in the "egypt" folder located in the "photos" folder at the root of the
web site.

Each _path segment_ can have optional _path parameters_ (also called
http://www.w3.org/DesignIssues/MatrixURIs.html[matrix parameters]) which
are located at the end of the _path segment_ after a ";", and separated
by ";" characters. Each parameter name is separated from its value by
the "=" character like this: "/file;p=1" which defines that the _path
segment_ "file" has a _path parameter_ "p" with the value "1". These
parameters are not often used — let's face it — but they exist
nonetheless, and we've even found a very good justification for their
use on a http://www.yahoo.com[Yahoo]
http://en.wikipedia.org/wiki/Representational_State_Transfer[RESTful]
http://developer.yahoo.com/social/rest_api_guide/uri-general.html[API
documentation]:

____
Matrix parameters enable the application to retrieve part of a
collection when calling an HTTP GET operation. See
http://developer.yahoo.com/social/rest_api_guide/partial-resources.html#paging-collection[Paging
a Collection] for an example. Because matrix parameters can follow any
collection path segment in a URI, they can be specified on an inner path
segment.
____

After the path segments we can find the _query_ which is separated from
the _path_ with a "?" character, and contains a list (separated by "&")
of parameter names and values separated by "=". For example "/file?q=2"
defines a _query parameter_ "q" with the value "2". This is used a lot
when submitting http://www.w3.org/TR/html401/interact/forms.html[HTML
forms], or when calling applications such as Google search.

Last in an HTTP URL is the _fragment_ which is used to refer not to the
whole HTML page but to a specific part within that file. When you click
on a link and the browser automatically scrolls down to display a part
which was not visible from the top of the page, you have clicked a URL
with a _fragment_ part.

[#URLgrammar]
=== URL grammar

The _http_ URL scheme was first defined in
http://tools.ietf.org/html/rfc1738[RFC 1738] (actually even before in
http://tools.ietf.org/html/rfc1630[RFC 1630]) and while the _http_ URL
scheme has not been redefined later the whole URL syntax has been
generalised into _Uniform Resource Identifiers_ (URIs) from a
http://tools.ietf.org/html/rfc1808[specification] which has been
http://tools.ietf.org/html/rfc2396[extended] a
http://tools.ietf.org/html/rfc2732[few times] to accommodate for
evolutions.

There is a grammar which defines how URLs are assembled, and how parts
are separated. For instance, the "://" part separates the _scheme_ from
the _host_ part. The _host_ and _path fragments_ parts are separated by
"/", while the _query_ part follows a "?". This means that certain
characters are _reserved_ for the syntax. Some are reserved for all
URIs, while some are only reserved for specific schemes. All _reserved_
characters that are used in a part where they are not allowed (for
instance a _path segment_ — a file name for example — which would
contain a "?" character) must be _URL-encoded_.

URL-encoding is the transformation of a character ("?") into a harmless
representation of this character which has no syntactic meaning in the
URL. This is done by converting the character into a sequence of bytes
in a specific http://en.wikipedia.org/wiki/Character_encoding[character
encoding], then writing these bytes in hexadecimal preceded by "%". A
question mark in URL-encoding is therefore "%3F".

We can write a URL pointing to the "to_be_or_not_to_be?.jpg" image as
such: "http://example.com/to_be_or_not_to_be%3F.jpg" which makes sure
that nobody would think there might be a _query_ part in there.

Most browsers nowadays _display_ the URLs by _decoding_ (converting
_percent-encoded_ bytes back to their original characters) them first,
while keeping them encoded when fetching them for the network. This
means users are almost never aware of such encoding.

Developers, or web page authors on the other hand have to be aware of
it, because there are many pitfalls.

[#CommonpitfallsofURLs]
== Common pitfalls of URLs

If you are working with URLs, it pays to know some of the most common
traps you should avoid. Here we give a non-exhaustive list of some of
those traps.

[#Whichcharacterencoding%3F]
=== Which character encoding?

URL-encoding does not define any particular character encoding for
percent-encoded bytes. Generally
http://en.wikipedia.org/wiki/ASCII[ASCII] alphanumeric characters are
allowed unescaped, but for reserved characters and those that do not
exist in ASCII (the French "œ" from the word "nœud" — "knot" — for
instance), we have to wonder which encoding to use when converting them
to percent-encoded bytes.

Of course the world would be easier if there were just
http://en.wikipedia.org/wiki/Unicode[Unicode], because *every* character
exists in this set, but this is
http://en.wikipedia.org/wiki/Universal_Character_Set[a set] — a list if
you will — and not an encoding _per se_. Unicode can be encoded using
several encodings such as http://en.wikipedia.org/wiki/UTF-8[UTF-8] or
http://en.wikipedia.org/wiki/UTF-16/UCS-2[UTF-16] (there are several
others), but then the problem is still there: which encoding should URLs
(generally URIs) use?

The standards do not define any way by which a URI might specify the
encoding it uses, so it has to be deduced from the surrounding
information. For HTTP URLs it can be the HTML page encoding, or HTTP
headers. This is often confusing and a source of many errors. In fact,
the http://tools.ietf.org/html/rfc3986[latest version of the URI
standard] defines that new URI schemes use
https://jira.lunatech.com/jira/browse/UTF-8[UTF-8], and that _host
names_ (even on existing schemes) also use this encoding, which really
rouses my suspicion: can the _host name_ and the _path_ parts really use
different encodings?

[#Thereservedcharactersaredifferentforeachpart]
=== The reserved characters are different for each part

Yes they are. Yes they are. Yes they are. (Yes they are).

For HTTP URLs, a space in a _path fragment_ part has to be encoded to
"%20" (not, absolutely not "+"), while the "+" character *in the path
fragment* part can be left unencoded.

Now in the _query_ part, spaces may be encoded to either "+" (for
backwards compatibility: do not try to search for it in the URI
standard) or "%20" while the "+" character (as a result of this
ambiguity) has to be escaped to "%2B".

This means that the "blue+light blue" string has to be encoded
differently in the _path_ and _query_ parts:
"http://example.com/blue+light%20blue?blue%2Blight+blue". From there you
can deduce that encoding a fully constructed URL is impossible without a
syntactical awareness of the URL structure.

Suppose the following Java code to construct a URL:

[source,java=nogutter]
----
String str = "blue+light blue";
String url = "http://example.com/" + str + "?" + str;
----

Encoding the URL is not a simple iteration of characters in order to
escape those that fall outside of the reserved set: we have to know
which reserved set is active for each part we want to encode.

This means that most URL-rewriting filters would be wrong if they decide
to take a URL substring from one _part_ into another without proper
encoding care. It is *impossible* to encode a URL without knowing about
its specific parts.

[#Thereservedcharactersarenotwhatyouthinktheyare]
=== The reserved characters are not what you think they are

Most people ignore that "+" is allowed in a _path_ part and that it
designated the plus character and not a space. There are other
surprises:

* "?" is allowed unescaped anywhere _within_ a _query_ part,
* "/" is allowed unescaped anywhere _within_ a _query_ part,
* "=" is allowed unescaped anywhere _within_ a _path parameter_ or
_query parameter_ value, and within a _path segment_,
* ":@-._~!$&'()*+,;=" are allowed unescaped anywhere _within_ a _path
segment_ part,
* "/?:@-._~!$&'()*+,;=" are allowed unescaped anywhere _within_ a
_fragment_ part.

While this is slightly nuts and
"`http://example.com/:@-._~!$&'()*+,=;:@-._~!$&'()*+,=:@-._~!$&'()*+,==?/?:@-._~!$'()*+,;=/?:@-._~!$'()*+,;==#/?:@-._~!$&'()*+,;=`"
is a valid HTTP URL, this is the standard.

For the curious, the previous URL expands to:

[cols=",",]
|===
|Part |Value
|Scheme |http
|Host |example.com
|Path |/:@-._~!$&'()*+,=
|Path parameter name |:@-._~!$&'()*+,
|Path parameter value |:@-._~!$&'()*+,==
|Query parameter name |/?:@-._~!$'()* ,;
|Query parameter value |/?:@-._~!$'()* ,;==
|Fragment |/?:@-._~!$&'()*+,;=
|===

Nuts.

[#AURLcannotbeanalysedafterdecoding]
=== A URL cannot be analysed after decoding

The syntax of the URL is only meaningful *before* it is URL-decoded:
after URL-decoding, reserved characters may appear.

For example "http://example.com/blue%2Fred%3Fand+green" has the
following parts before decoding:

[cols=",",]
|===
|Part |Value
|Scheme |http
|Host |example.com
|Path segment |blue%2Fred%3Fand+green
|Decoded Path *segment* |blue/red?and+green
|===

Thus, we are looking for a file called "blue/red?and+green", *not* for
the "red?and+green" file of the "blue" folder.

If we decode it to "http://example.com/blue/red?and+green" before
analysis the parts would give:

[cols=",",]
|===
|Part |Value
|Scheme |http
|Host |example.com
|Path segment |blue
|Path segment |red
|Query parameter name |and green
|===

This is clearly wrong: analysis of reserved characters and URL parts has
to be done before URL-decoding. The implication is that URL-rewriting
filters should never decode a URL before attempting to match it *iff*
reserved characters are allowed to be URL-encoded (which may or may not
be the case depending on you application).

[#DecodedURLscannotbereencodedtothesameform]
=== Decoded URLs cannot be reencoded to the same form

If you decode "http://example.com/blue%2Fred%3Fand+green" to
"http://example.com/blue/red?and+green" and proceed to encode it (even
with an encoder which knows about each syntactical URL part) you will
get "http://example.com/blue/red?and+green" because that is a _valid_
URL. It just happens to be very different from the original URL we
decoded.

[#HandlingURLscorrectlyinJava]
== Handling URLs correctly in Java

When you have mastered your black belt in _URL-fu_ you will notice that
there are still quite a few Java-specific pitfalls when it comes to
URLs. The road to URL handling correctness is not for the faint of
heart.

[#Donotuse%7B%7Bjava.net.URLEncoder%7D%7Dor%7B%7Bjava.net.URLDecoder%7D%7DforwholeURLs]
=== Do not use `java.net.URLEncoder` or `java.net.URLDecoder` for whole URLs

We are not kidding. These classes are not made to encode or decode URLs,
as their API documentation
http://download.java.net/jdk7/docs/api/java/net/URLEncoder.html[clearly
says]:

____
Utility class for HTML form encoding. This class contains static methods
for converting a String to the `application/x-www-form-urlencoded` MIME
format. For more information about HTML form encoding, consult the HTML
specification.
____

This is not about URLs. At best it resembles the _query_ part encoding.
It is wrong to use it to encode or decode entire URLs. You would think
the standard JDK had a standard class to deal with URL encoding properly
(part by part, that is) but either it is not there, or we have not found
it, which lures a lot of people into using `URLEncoder` for the wrong
purpose.

[#DonotconstructURLswithoutencodingeachpart]
=== Do not construct URLs without encoding each part

As we have already stated: fully constructed URLs cannot be URL-encoded.

Take the following code for instance:

[source,java=nogutter]
----
String pathSegment = "a/b?c";
String url = "http://example.com/" + pathSegment;
----

It is impossible to convert "http://example.com/a/b?c" back to what it
should have been if "a/b?c" was meant to be a path segment, because it
happens to be a valid URL. We have already explained this earlier.

Here is the proper code:

[source,java=nogutter]
----
String pathSegment = "a/b?c";
String url = "http://example.com/"
            + URLUtils.encodePathSegment(pathSegment);
----

We are now using a utility class `URLUtils` which we had to make
ourselves for lack of finding an exhaustive one available online fast
enough. The previous code will give you the properly encoded URL
"http://example.com/a%2Fb%3Fc".

Note that the same applies to the query string:

[source,java=nogutter]
----
String value = "a&b==c";
String url = "http://example.com/?query=" + value;
----

This will give you "http://example.com/?query=a&b==c" which is a valid
URL, but not the "http://example.com/?query=a%26b==c" we wanted.

[#DonotexpectURI.getPath%28%29]
=== Do not expect http://download.java.net/jdk7/docs/api/java/net/URI.html#getPath()[URI.getPath()] to give you structured data

Since once a URL has been decoded, syntactical information is lost, the
following code is wrong:

[source,java=nogutter]
----
URI uri = new URI("http://example.com/a%2Fb%3Fc");
for(String pathSegment : uri.getPath().split("/"))
  System.err.println(pathSegment);
----

It would first decode the path "a%2Fb%3Fc" into "a/b?c", then split it
where it should not have been split into _path segment_ parts.

The correct code of course uses the
http://download.java.net/jdk7/docs/api/java/net/URI.html#getRawPath()[undecoded
path]:

[source,java=nogutter]
----
URI uri = new URI("http://example.com/a%2Fb%3Fc");

for(String pathSegment : uri.getRawPath().split("/"))
  System.err.println(URLUtils.decodePathSegment(pathSegment));
----

Do note that path parameters will still be present: deal with them if
required.

[#DonotexpectApacheCommonsHTTPClient%27s%7B%7BURI%7D%7Dclasstogetthisright]
=== Do not expect Apache Commons HTTPClient's `URI` class to get this right

The http://hc.apache.org/httpclient-3.x/[Apache Commons HTTPClient 3]'s
http://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/URI.html[URI]
class uses http://commons.apache.org/codec/[Apache Commons Codec]'s
`URLCodec` for URL-encoding, which is wrong as their
http://commons.apache.org/codec/api-release/org/apache/commons/codec/net/URLCodec.html[API
documentation mentions] since it is just as wrong as using
`java.net.URLEncoder`. Not only does it use the wrong encoder, but it
also
http://svn.apache.org/repos/asf/httpcomponents/oac.hc3x/trunk/src/java/org/apache/commons/httpclient/URI.java[decodes
each part as if they all had the same reserved set].

[#FixingURLencodingateverylevelinawebapplication]
== Fixing URL encoding at every level in a web application

We have had to fix quite a few URL-encoding issues in our application
lately. From support in Java, down to the lower level of URL rewriting.
We will here list a few of changes which were required.

[#AlwaysencodeURLsasyoubuildthem]
=== Always encode URLs as you build them

In our HTML files, we replaced all occurrences of this:

[source,java=nogutter]
----
var url = "#{vl:encodeURL(contextPath + '/view/' + resource.name)}";
----

with:

[source,java=nogutter]
----
var url = "#{contextPath}/view/#{vl:encodeURLPathSegment(resource.name)}";
----

And similarly for query parameters.

[#MakesureyourURLrewritefiltersdealwithURLscorrectly]
=== Make sure your URL-rewrite filters deal with URLs correctly

http://tuckey.org/urlrewrite/[Url Rewrite Filter] is a URL rewriting
filter we use in http://www.seamframework.org[Seam] to transform pretty
URLs into application-dependent URLs.

For example, we use it to rewrite
`http://beta.visiblelogistics.com/view/resource/FOO/bar` into
`http://beta.visiblelogistics.com/resources/details.seam?owner=FOO&name=bar`.
*Obviously* this involves taking some strings from one URL part to
another, which means we have to decode from the _path segment_ part and
reencode as a _query value_ part.

Our initial rule looked as follows:

[source,xml=nogutter]
----
<urlrewrite decode-using="utf-8">
 <rule>
  <from>^/view/resource/(.*)/(.*)$</from>
  <to encode="false">/resources/details.seam?owner=$1&name=$2</to>
 </rule>
</urlrewrite>
----

It turns out that there are only two ways to deal with URL-decoding in
Url Rewrite Filter: either every URL is decoded prior to doing the rule
matching (the `<to>` patterns), or it is disabled and each rule has to
deal with decoding. In our opinion the latter is the sanest option,
especially if you move URL parts around, and/or want to match _path
segments_ which may contain URL-encoded path separators.

Within the replacement pattern (the `<to>` patterns) you can then deal
with URL encoding/decoding using the inline functions `escape(String)`
and `unescape(String)`.

As of this writing, Url Rewrite Filter Beta 3.2 contains several bugs
and limitations which blocked our progress towards URL-correctness:

* URL decoding was done using `java.net.URLDecoder` (which is wrong),
* the `escape(String)` and `unescape(String)` inline functions used
`java.net.URLDecoder` and `java.net.URLEncoder` (which is not specific
enough and will only work for entire query strings, beading in mind any
"&" or "=" will not be encoded).

We therefore made a
http://code.google.com/p/urlrewritefilter/issues/detail?id=27&colspec=ID[big
patch] fixing a few issues like URL decoding, and adding the inline
functions `escapePathSegment(String)` and `unescapePathSegment(String)`.

We can now write the _almost_ correct:

[source,xml=nogutter]
----
<urlrewrite decode-using="null">
 <rule>
  <from>^/view/resource/(.*)/(.*)$</from>
  <-- Line breaks inserted for readability -->
  <to encode="false">/resources/details.seam
                     ?owner=${escape:${unescapePath:$1}}
                     &name=${escape:${unescapePath:$2}}</to>
 </rule>
</urlrewrite>
----

It is only _almost_ correct because our patch still lacks a few things:

* the inline escaping/unescaping functions should be able to specify the
encoding as either fixed (this is already done) or by determining it
from the HTTP call (not supported yet),
* the old `escape(String)` and `unescape(String)` inline functions were
left intact and still call `java.net.URLDecoder` which is wrong as it
will not escape "&" or "=",
* we need to add more part-specific encoding/decoding functions,
* we need to add a way to specify the decoding behaviour _per-rule_ as
opposed to globally in `<urlrewrite>`.

As soon as we get the time, we will send a second patch.

[#UsingApachemodrewritecorrectly]
=== Using Apache mod-rewrite correctly

http://httpd.apache.org/docs/2.0/mod/mod_rewrite.html[Apache
mod-rewrite] is an http://httpd.apache.org/[Apache web server] module
for URL-rewriting which we use to proxy all our
`http://beta.visiblelogistics.com/foo` traffic to
`http://our-internal-server:8080/vl/foo` for instance.

This is the last thing to fix, and just like Url Rewrite Filter, it
defaults to decoding the URL for us, and reencoding the rewritten URL
for us, which is wrong, as *decoded URLs cannot be reencoded*.

There is one way to get around this however, at least in our case since
we are not switching one URL part for another, we do not need to decode
a _path_ part and reencode it into a _query_ part for example: do not
decode and do not reencode.

We accomplished it by using `THE_REQUEST` for URL-matching which is the
full HTTP request (including the HTTP method and version) undecoded. We
just take the URL part after the host, change the host and prepend the
_/vl_ prefix, and tada:

[source,code-xml]
----
...

# This is required if we want to allow URL-encoded slashes a path segment
AllowEncodedSlashes On

# Enable mod-rewrite
RewriteEngine on

# Use THE_REQUEST to not decode the URL, since we are not moving
# any URI part to another part so we do not need to decode/reencode

RewriteCond %{THE_REQUEST} "^[a-zA-Z]+ /(.*) HTTP/\d\.\d$"
RewriteRule ^(.*)$ http://our-internal-server:8080/vl/%1 [P,L,NE]
----

[#Conclusion]
== Conclusion

We hope to have clarified some URL myths and common mistakes. Short of
clarifying them, making it obvious that it is not as simple as some
people think will suffice. We have illustrated common mistakes in Java,
and in the whole chain of a web application deployment. Now everyone is
a URL expert and we hope never to see related bugs again. Please SUN,
please: add standard support for URL encoding/decoding *part by part*.


