= Benelux JBoss User Group, 27 February 2009
pepite
v1.0, 2009-02-03
:title: Benelux JBoss User Group, 27 February 2009
:tags: [java,event,jbug]

We would like to invite you to our **fifth Benelux
JBoss User Group meeting**: an evening of free technical sessions
presented by JBoss and RealDolmen developers.

We will meet in the Lunatech Research's office in Rotterdam.

* Date: Friday, 27 February 2009
* Time: Arrival 1600-1630, presentations start 1630, finish 1900-1930
* Location: http://lunatech-research.com/contact

*Programme*

The programme will begin with a**JBoss Seam case study** by *Joris de
Winne* and *Jeroen Verhulst* from RealDolmen. The talk will explain the
basic concepts of JBoss Seam covering how to create components,
injection, outjection, scope levels, security... In addition, it will
give an overview of the pros and cons of the technology illustrated by a
practical example. Special attention will be paid to how to test a JBoss
Seam application. +

In the second presentation, *Mark Proctor*, lead for *JBoss Drools*,
will talk about Rules, Workflow and Event Processing (often referred to
as event stream processing or complex event processing) are at the heart
of the Business Logic for most enterprises. Each one provides a
declarative environment to model business problems, but is limited in
the scope and range of problems it can define. Typically an enterprise
will source each product from a different vendor and at some level tries
to integrate the three. This integration is often very limited and
superficial, such as processes only using rules for stateless decision
services. This session presents the Business Logic integration Platform
(BLiP) concept which offers an integrated and unified approach.

Of course, beer and networking are also part of the programme ;)

Please http://www.lunatech-research.com/event/register/jbug5[register]
as soon as possible as we have a limited number of seats.
