= How to get a job at Lunatech
PeterHilton
v1.0, 2010-08-05
:title: How to get a job at Lunatech
:tags: [employment,opinion]

http://www.cloudera.com/blog/2010/07/how-to-get-a-job-at-cloudera/[How to Get a Job at
Cloudera]
is an excellent article that explains to job candidates how to be more
interesting than just a CV in the mail, and why going through a
recruitment agency puts you at a big disadvantage. You could just read
the article with Lunatech in mind, because the same things are true here
as well, and because we are also interviewing people for our http://www.lunatech-research.com/content/java-ee-developer-vacancies[Java EE
developer
vacancies]
at the moment. However, it is worth re-telling the story from our point
of view, which is what this article is." ---

[[recruiters]]
== Recruiters from our point of view

Lunatech either gets a CV direct from the candidate or via a third-party
- usually a recruiter who is trying to ‘place’ the candidate, for a fee.
The candidate is worse off when a recruiter is involved. Cloudera sum
this up pretty well in their article:

____
Contingency recruiters get paid by the hiring company when the candidate
they introduce gets the job. The amount they get paid varies a little
bit, but is generally a quarter to a third of the annual salary of the
person they place. That means that a software developer who earns $80K a
year shows up with a $20,000 price tag, minimum, due and payable to the
recruiter, up front. If you are that software developer, you need to be
not merely as good as the rest of the candidates we are looking at. It
is not even enough to be a little bit better. You need to be so
astonishingly good that you are worth our writing a fat check to a third
party on your very first day in the office. And, honestly, if you are
that good, how come we do not know about you already?
____

This matches our experience exactly. For example, a year or two ago, a
recruiter contacted us about a candidate. The candidate, who I shall
call ‘Tom’ (his real name), was a Java developer working for a large IT
company in Rotterdam and was ‘looking for a new challenge’ and ‘very
interested in Lunatech’. This sounds great, but there are a couple of
problems.

[[costly]]
== Candidates who cost more

First, the recruiter’s €10000 - €15000 fee would have made hiring Tom
very expensive. This is not out of the question, especially for large
organisations whose human resources departments spend a lot more than
that to hire each new employee. Lunatech, on the other hand, is a small
agile organisation where one of the senior developers manages
recruitment directly, with very little overhead.

Tom would have to have been exceptionally good to justify the
recruiter’s fee on top of the usual risk of hiring a new employee, but
we never found out because we could only justify the cost if we had a
good chance of putting him on paid work shortly after starting, and we
did not need someone for a project that month. After all, Lunatech is a
small company and does not start many new projects every month.

[[indifferent]]
== Candidates who go elsewhere first

A second problem is the notion that Tom was ‘very interested in
Lunatech’, given that he did not contact us directly. There are other
explanations, but the most likely is simply that Tom had never actually
heard of Lunatech or found out anything about us, and that the recruiter
was telling the same pitch to every software company in Holland.

Furthermore, even if we suppose that Tom really was specifically
interested in Lunatech, why did he not contact us directly? Perhaps it
is just easier to use a recruiter, from the candidate’s point of view:
the recruiter does the work of making contact and the initial pitch, and
someone else pays.

These possibilities are not the biggest problem: even if it means that
recruiters’ candidates tend to be somewhat indifferent, lazy or shy, the
candidates could be so good at writing code that it would be worth
interviewing them.

[[misguided]]
== Misguided candidates

The biggest problem is the possibility that candidates are looking for
jobs via recruiters because they (wrongly) believe that this approach is
more likely to get them interviews. Lunatech does not have a special
relationship with any particular recruiters, and there is no up-side
from our point of view. Candidates who believe that a recruiter is more
likely to get them an interview at Lunatech have just been talking to
more recruiters than hiring managers.

Tom’s situation, meanwhile, would have been different if he had
contacted us directly. We would have invited him for an interview at the
earliest opportunity, and might have offered him his ideal job.

[[market]]
== A sellers’ market

At the moment it is a candidates’ market, and we get fewer applicants
than we would like. Instead, a good candidate can reasonably expect to
be invited to interviews at several companies, and choose between a
choice of job offers. The smart candidates are therefore interviewing
several companies, at the same time as being interviewed themselves, to
find out who they want to work for.

However, this does not mean it makes sense to be lazy about applying for
jobs: the lazy or less smart candidates are effectively screening
companies on how much they spend on recruitment, which are not
necessarily the best places to work as a programmer. Let’s face it: the
more a company spends on job adverts and recruiter fees, the less likely
they are to make sure that each developer has a seriously powerful
workstation with
http://www.codinghorror.com/blog/2004/06/multiple-monitors-and-productivity.html[enough
monitors].

[[Conclusion]]
== Conclusion

In reality, if you are a ‘Tom’ (or in fact the real Tom), then we would
love to talk to you about jobs at Lunatech, to find out whether we are
each other’s ideal employee and employer.

Just to be clear, we do not hate recruiters - some of them are really
nice people. It’s just that a recruiter is a sales person with a slick
pitch who would sell you her grandmother if she could. Even if her
grandmother is a Visual Basic programmer who still codes ActiveServer
Pages web applications in VBScript. Besides, the economics of the
situation work against recruiters.

As a job applicant you are welcome to give your CV to a recruiter and
see what you end up with, but if you want to get a job at Lunatech, it
is far faster and simpler to send your CV to employment@lunatech.com.

