= Activiti next-generation Business Process Management and work-flow
PeterHilton
v1.0, 2010-05-18
:title: Activiti next-generation Business Process Management and work-flow
:tags: [bpm,java]

http://www.alfresco.com/media/releases/2010/05/activiti_bpm/[Yesterday's
launch] of
http://www.activiti.org/[Activiti] starts a new generation of business
process management (BPM) software that will disrupt the existing BPM
engine landscape. Activiti promises to be the ideal choice for using BPM
in commercial application development, because it is both based on
open-standards and distributed under a liberal open-source license. More
than anything else, these two aspects of Activiti make it more
interesting for commercial software development than either other open
source BPM platforms that have more restrictive licenses, or
closed-source commercial offerings that carry the heavy price of vendor
lock-in.

The benefits of an open-source solution require no explanation; the
http://www.activiti.org/faq.html[Activiti FAQ] explains the license
choice:

____
Activiti is licensed under the Apache License 2.0 to encourage
widespread usage and adoption of the Activiti BPM engine and BPMN 2.0.
By choosing such a liberal licence, we want to emphasize our goal of
commoditizing BPM technology.
____

Activiti is the result of a collaboration between
http://www.alfresco.com/[Alfresco] and a new development team:
http://processdevelopments.blogspot.com/[Tom Baeyens], formerly jBPM
project lead, and http://www.jorambarrez.be/[Joram Barrez], former jBPM
core developer. This means that Activiti is no mere new entrant in the
BPM world: Activiti is the result of both the theoretical underpinnings
of the jBPM platform and Alfresco's experience of delivering BPM in its
Enterprise Content Management product suite.

When we met Tom and Joram to discuss this new venture, they made it
clear that a new approach is essential to take BPM from its initial
niche software status to widespread adoption in business software. While
BPM initially gained popularity as a stand-alone software category,
business processes and work-flow are aspects of most business software
and integrating embeddable BPM will be a key element in reducing the
cost of business software development.

They went on to explain how existing BPM platforms are unable to meet
this need, leaving a huge gap in the market for a next generation
solution. Alfresco is the organisation that has stepped up to fill this
gap, having recognised that the world needs this kind of solution; there
will be more commercial organisations that require an embeddable BPM
solution with a more liberal open-source license.
http://www.activiti.org/[Activiti] is that solution.

