= Turkish Play framework community
PeterHilton
v1.0, 2011-07-27
:title: Turkish Play framework community
:tags: [playframework]

Last week a new Play framework discussion group was announced on Google
Groups. There is already a
https://groups.google.com/forum/#!forum/play-framework[play-framework]
group - the new
https://groups.google.com/forum/#!forum/play-framework-tr[play-framework-tr]
group is in Turkish. It turns out that there have also been attempts to
start groups in other languages:
https://groups.google.com/forum/#!forum/playframework-cn[playframework-cn]
(Chinese), https://groups.google.com/forum/#!forum/play_ja[play-ja]
(Japanese) and
https://groups.google.com/forum/#!forum/ru-play-framework[ru-play-framework]
(Russian).

*Update: since this article was published, a
https://groups.google.com/forum/#!forum/play-latam[play-latam]
(Latin-America) group has started as well.*

None of these groups is really active yet, but this is certainly the
start of the Play framework community’s next growth spurt. This happens
when a single language group contains a critical mass of developers that
can support a developer community in that language, which then enables
developers who are less comfortable asking questions in English to
participate. Any developer community that successfully makes this
transition can then grow rapidly, as the community grows enough to
establish a market for its own conferences, documentation translations,
books and ultimately jobs.

The Play framework community is still in the initial global phase, and
it is early days for the Chinese-, Japanese-, Turkish- and
Russian-language communities. In any case, it is exciting to see Play
well on the way to world-domination.


