= Riviera DEV
FroMage
v1.0, 2011-08-15
:title: Riviera DEV
:tags: [event,java]

Lunatech Research, with the http://rivierajug.org[Riviera
JUG] and the http://inria.fr[INRIA] French
research institute are organising the http://rivieradev.fr[Riviera
DEV] conference in Sophia-Antipolis on the 20/21
of October 2011.

As you all know the Riviera JUG has been holding monthly conferences for
more than two years now with an average of 50 java developers every
month, as well as yearly larger conferences with an average of 150
people, such as "Sophia fait sa Java" in 2009 and "Sophia Conf 2010"
last year.

This year we're launching our yearly conference under a new name:
*Riviera DEV*, which we expect we will keep every year this time. And
we're growing again, with *two days of conference* on the *Thursday 20
and Friday 21 of October*, featuring *33 conferences* split in *3
parallel tracks* and a common keynote. We will have a *Java* track, a
more general *Web* track and a *Research* track held by INRIA where we
expect research and industry attendees will meet.

A few speakers have already been confirmed, including our very own
colleague Nicolas Leroux who will present
http://rivieradev.fr/application/talk?id=128[Play! Framework], but many
more will be announced in the coming weeks, including some real
superstars, so watch our for
http://rivieradev.fr/application/schedule[our program].

Registration is expected to open early September.
