= Øredev - recommended presentations
hilton
v1.0, 2012-11-22
:title: Øredev - recommended presentations
:tags: [conference]

While http://blog.lunatech.com/2012/11/14/oredev-2012-playframework-video[I was at
Øredev]
earlier this month I took the opportunity to talk to the other speakers
and catch some good presentations. For everyone who wasn’t there, Øredev
have published the slides and video from the presentations at http://vimeo.com/user4280938[Øredev
Conference on Vimeo]. Here are some
recommendations.

Note that some of the presentations take several slides to get going,
and the track hosts’ introductions don’t really add much, so the
impatient should skip the first five minutes of each video.

*Best keynote:*
http://oredev.org/2012/sessions/the-rebellion-imperative[The rebellion
imperative], by Reginald Braithwaite
(http://twitter.com/raganwald[@raganwald]), is one of several keynotes
at the conference, which all had a ‘rebellion’ theme. Among the mixed
interpretations, I especially enjoyed this talk about rebellion in
software product marketing. This is a good keynote topic for encouraging
software developers to broaden their interests. @Raganwald is an
entertaining speaker whose experience and worldliness enriches what he’s
talking about. Also, he’s very entertaining, so it’s a shame that the
audience remained so silent throughout his jokes. The _Marketing
Warfare_ book he mentions could be one of the useful
http://blog.lunatech.com/2008/02/18/marketing-books-developers[marketing
books for software developers].

*Best new methodology:*
http://oredev.org/2012/sessions/programmer-anarchy[Programmer Anarchy],
by Fred George (http://twitter.com/fgeorge52[@fgeorge52]), trumped all
sorts of other presentations by going beyond both rebellion and agile
software development in general, to describe a whole new level for
software developers to aspire to. This talk is inspiration for agile
hipsters who think they're done because they did one successful Scrum
project, and didn't realise that there's more. Most people couldn’t get
away with the audacity of the story, or even the cheesy over-use of
sparkly slide animations, but Fred

*Best technical content:*
http://oredev.org/2012/sessions/http-caching-101[HTTP Caching 101], by
Sebastien Lambla (http://twitter.com/serialseb[@serialseb]), is the best
technical talk I went to at Øredev, partly because it’s a relevant topic
for me and partly because it had a great mix of technical detail,
humour, useful things to do, ponies and unicorns. Unfortunately, I
arrived late so I missed the warm up exercise at the start.

*Best case study:*
http://oredev.org/2012/sessions/how-being-customer-centric-improves-it-success-a-case-study[How
being customer-centric improves IT success], by Elizabeth Harrin
(http://twitter.com/pm4girls[@pm4girls]), is a project management case
study that made a break from the tech talks. This presentation was also
a refreshing break from agile software development talks with bogus
theories and little actual experience: instead this presentation is a
clear and articulate story that makes a difficult thing (actually
talking to your customers and software users) sound easy, and challenges
complex methods that ultimately focus on the wrong thing. When I talked
to Elizabeth, I was impressed by the humility of her no-nonsense
approach to project management, which also comes across in her blog,
http://www.pm4girls.elizabeth-harrin.com/[A Girl's Guide to Project
Management].

*Best conceptual model:*
http://oredev.org/2012/sessions/reinventing-software-quality[Reinventing
software quality], by Gojko Adzic
(http://twitter.com/gojkoadzic[@gojkoadzic]), is a thought-provoking
general development presentation, and probably included the one with the
best jokes. However, all of the humorous asides were really building up
to a transliteration of Maslow's hierarchy of needs for software
development that provides a more expressive structure for thinking about
software quality than the usual approaches.

*Most practical:*
http://oredev.org/2012/sessions/api-usability-think-of-the-humans[API
Usability: Think of the humans!] by Catherine Powell
(http://twitter.com/cmpowell[@cmpowell]), was the most directly useful
technical talk (i.e. that includes code on slides) I went to, despite
being the least sexy topic. I went to this talk because after talking to
Catherine about a variety of topics, I realised that she has plenty to
say about a lot of interesting experience, and is articulate enough to
say it well. This is the kind of presentation that never seems difficult
and never seems to introduce you to anything new, and yet includes a
surprising number of ‘aha’ moments and ideas about how to write code
differently. Of course, if you’re paying attention, there’s a deeper
point that probably is new.

*Best vision:*
http://oredev.org/2012/sessions/its-not-you-its-them-why-programming-languages-are-hard-to-teach[It's
Not You, It's Them: Why Programming Languages Are Hard To Teach], by Zed
Shaw (http://twitter.com/zedshaw[@zedshaw]), is an entertaining talk by
a great speaker about an unexpected topic that you didn’t know you cared
about: programming education.

*Best product:*
http://oredev.org/2012/sessions/a-deep-look-into-the-event-store[A deep
look into the Event Store], by Greg Young
(http://twitter.com/gregyoung[@gregyoung]), is a classic tech conference
presentation: a deep dive on the technical implementation of a software
product that’s part of a cool new architecture that I’m interested in
but not using yet: event sourcing, in this case. During the talk I was
captivated by the details and Greg’s compelling style, but ultimately
disappointed to learn that Event Store runs on .NET. However, when I
talked to Greg later it turns out that his preferred runtime is Mono on
Linux, so I shouldn’t discount it just yet. For now, though, a simpler
event store such as https://github.com/sbtourist/Journal.IO[Journal.IO]
suits my needs.

*Best book:*
http://oredev.org/2012/sessions/business-patterns-for-software-developers[Business
Patterns for Software Developers], by Allan Kelly
(http://twitter.com/allankellynet[@allankellynet]), presented the key
ideas from his book of the same name. This is an intriguing business
presentation, if you’re thinking about how to be successful in the
software business, and I’m looking forward to reading the book.

*Best code:* http://oredev.org/2012/sessions/jquery-combinators[jQuery
Combinators], by Reginald Braithwaite
(http://twitter.com/raganwald[@raganwald]), is a code-walkthrough
presentation about a functional coding style in JavaScript. The
presentation was automatically cool, because it was an implementation of
http://en.wikipedia.org/wiki/Conway%27s_Game_of_Life[Conway’s Life], but
sometimes hard to follow because Raganwald cheated by scrolling through
finished code instead of typing it, which was often too fast. However,
he has now published
http://weblog.raganwald.com/JQuery-Combinators/life/life.html[annotated
source code], which makes it much easier to understand.

*Best ending:*
http://oredev.org/2012/sessions/test-driven-android[Test-Driven
Android], by Cheesy (http://twitter.com/chzy[@chzy] a.k.a. Jeff Morgan),
is a presentation on a topic that is not at all relevant to me. I had to
attend anyway, though, after I sat next to Cheesy while he was preparing
the last slide: an Abba photo, Dancing Queen audio and (a very few
members of the) audience dancing.

Øredev has done well to make so many presentations freely-available
on-line, and there are some excellent talks available. This is great
when you keep missing half a presentation because you kept getting into
excellent conversations when you were actually there.

https://plus.google.com/107170847819841716154/posts/EVLVfk1Emz9[Comments
on Google+]
