= Third Monthly Clojure Meetup at Lunatech
vijaykiran
v1.0, 2013-05-23
:title: Third Monthly Clojure Meetup at Lunatech
:tags: [event,clojure]

Third Monthly Rotterdam/The Hague Clojure Meetup at Lunatech

Yesterday it was time for yet another monthly meetup of
http://www.ehrdclj.org[EHRD.clj] here at Lunatech.

We started with _This Month in Clojure_ discussing new libraries in
Clojure - from https://github.com/mikera/imagez[imagez] to
https://github.com/phillord/tawny-owl[Tawny-OWL].

For Library of the month https://twitter.com/skuro[Carlo Sciolla],
showed us how to get started with
https://github.com/liquidz/misaki[Misaki] and how he uses Misaki to run
http://amsclj.nl/[Amsterdam Clojure Meetup Website].

The main feature of the evening was the Dojo coordinated by Chris
Wilson. We had a quick intro to https://github.com/marick/Midje[Midje]
and tried a simple TDD hacking dojo session - _Converting Arabic
numerals to Roman numerals_. It was a
http://www.meetup.com/ehrd-clj/events/106662762/[fun evening] with lots
of interesting discussions and I think everyone liked participating in
the Dojo.

Don’t forget to http://www.meetup.com/ehrd-clj/events/106662772/[RSVP]
to our next monthly meetup if you are interested in all things Clojure.
