= Fast Track to Scala - Training
fcanedo
v1.0, 2016-01-18
:title: Fast Track to Scala - Training
:tags: [scala]

On Feb 4 and 5th https://twitter.com/fcanedo/[Francisco Canedo], Senior Developer at Lunatech and a Typesafe certified trainer, will be teaching Typesafe’s Fast Track to Scala Course at our office.

This course is designed to give experienced developers the know-how to confidently start programming in Scala. The course ensures you will have a solid understanding of the fundamentals of the language, the tooling and the development process as well as a good appreciation of the more advanced features. If you already have Scala programming experience, then this course could be a useful refresher, yet no previous knowledge of Scala is assumed.

See Typesafe's http://www.typesafe.com/services/training[training page] for more information on course program. 

The course starts each day at 9:00 with breakfast, lunch is also provided, and ends between 17:00 and 18:00 depending on the needs of the students and costs €600 per person.

If you are interested in joining the course, please contact us by sending a mail to training@lunatech.com or tweet us https://twitter.com/lunatechlabs[@LunatechLabs]