= Meet and Greet and Scala Days review
Antoine Laffez
v1.0, 2016-06-24
:title: Meet and Greet and Scala Days review
:tags: [scala,event,voxxeddays]

After the Voxxed days Luxembourg, the 22 of June (National holiday) an informal Meet & Greet, sponsored by Lunatech and YaJUG took place in the brasserie “Le Neumünster”. 

We shared some beers with all of the organizer team and the speakers and saw an amazing firework show during the event which set ablaze the clear sky. The streets of Luxembourg city were crowded and we just realized that was a time suspended moment that made life so good...anyway. This first edition of Voxxed was a great success and we convey our thanks to the organizer for that, for sure the event will be bigger in the coming year(s) and we are kept in suspense. They promised us to start working on the second edition within three weeks. We can wish them a good holiday during this time.

Meanwhile in the Lunatech office, Bart Schuller made a Scala Days Berlin review at the Rotterdam functional meetup where he explained some technical details. The Scala community was eagerly expecting the Scala Days. In Fact, Martin Odersky, the creator was part of it as a keynote speaker. More than 1000 enthusiastic Scala developers were in Berlin and the event was completely sold out. All of Lunatech were present and our people spent three days of bliss between the Scala conference and the Giant frühsthück. 

As you can see the month of June was very busy and the next Scala dedicated event will be hosted in Lyon (Scala i.o) on 27th and 28th of October. Summer is here but we are not on holiday yet… some more news to come during these beautiful days. If you want to be part of it next year you can join us and keep in touch for any advice. And remember that we LOVE Scala