= Summer Fast Track To Scala Training By Lunatech
Antoine Laffez
v1.0, 2016-06-06
:title: Summer Fast Track To Scala Training By Lunatech
:tags: [scala,event]

On July 29th and 30th Sietse de Kaper (https://twitter.com/targeter[@Targeter]), Senior Software Engineer at Lunatech and Lightbend-certified trainer, will be teaching Lightbend’s Fast Track to Scala Course in our Rotterdam office. 

Scala is the technology of choice for a vibrant open-source ecosystem, including popular platforms and frameworks such as Spark, Kafka, Akka, Finagle, Cats, and Play, to name just a few. We estimate that currently more than half a million developers are using Scala.

This course is designed to give experienced developers the know-how to confidently start programming in Scala. The course ensures you will have a solid understanding of the fundamentals of the language, the tooling and the development process as well as a good appreciation of the more advanced features. If you already have Scala programming experience, then this course could be a useful refresher, yet no previous knowledge of Scala is required.

The course will start daily at 9:00 at our office in Rotterdam and will include breakfast and lunch. Depending on the needs of the students the day will end between 17:00 and 18:00. For more information about what will be handled in this training please see the http://www.lightbend.com/services/training[Lightbend training page]. The cost per person is €800.

If you are interested in joining the course, please contact us by sending a message to mailo:training@lunatech.com[training@lunatech.com] or tweet us https://twitter.com/lunatechlabs[@LunatechLabs].

We are delighted to welcome you!

Baan 743011 CD RotterdamCall Us : +31 10 750 2600