= A Journey Into Google Cloud At Devoxx
Xavier Tordoir
v1.0, 2018-11-19
:title: A Journey Into Google Cloud At Devoxx
:tags: [event]

Visiting Devoxx with Lunatech Team, Xavier Tordoir, Data scientist at Lunatech tried the Google Cloud platform exercises at Google booth:

Google was a sponsor of Devoxx 2018 and their booth was dedicated to the Google cloud platform. A few Chromebooks were available there to run through various tutorials, hands-on with the UI and tools. Between 10 and 30 minutes sessions would allow to solve one specific problem to pick from a list of about 25, including storage, VMs and containers, compute, SQL, BigData or AI.

== Some Examples Of The Learning Tour You Could Follow:

_Gcloud introduction_

Get familiar with the UI and the Gcloud tool, create projects and manage authentication. The Gcloud shell gives access to a VM terminal from the browser, with Gcloud installed to manage the projects.

_Deploy a java application with Kubernetes_

This exercise lets you create a Kubernetes cluster, and edit some java application project, with the online code editor. The application is a simple web page, dockerized and published to a private docker repo before being deployed with Kubernetes. A service with load balancing is created to expose the app to the world, then scaling up and down and application update is covered, very interesting practical intro to Kubernetes.

_Pub/Sub with Spring_

Gcloud has a Pub/Sub engine available for BigData, this tutorial guides through creating topics and run Spring applications, one publisher, and one subscriber.

_Speech API_

Google has artificial intelligence APIs, providing pre-trained models to conduct specific tasks, for example, speech-to-text function.

This tutorial teaches how to activate the AI API for your project, create an API key and submit requests to transform recorded spoken sentences in written text, in English and French. _Cloud Vision API_

This example shows different labelling functions for images, like classifying objects visible on the image, detect faces or even infer the location of the where the shot was taken!

_Scan images and video content_

This tutorial builds a processing pipeline, integrating Pub/Sub, cloud functions, BigQuery and Cloud Vision and Video Intelligence APIs. Image or video files dropped into a storage bucket trigger an event to start processing the file and label it for search safety scoring (should the content be filtered).
