= Reactive Summit Montreal 2018
Antoine Laffez
v1.0, 2018-10-19
:title: Reactive Summit Montreal 2018
:tags: [event]


Lunatech is heading off to Canada, with a delegation of 6 people, including our Lunatech International's CEO, Nicolas Leroux and our General Manager France, Nicolas Martignole. Organized by https://www.lightbend.com/[Lightbend], the https://www.reactivesummit.org/[Reactive Summit] Montreal, which will take place from October 22nd to 24th will welcome international speakers:  Lightbend's CTO, Victor Klang will talk about "The Convergence of Stream Processing and Microservice Architecture" in its Monday's keynote October 22nd in the main "ballroom".

There will be plenty of talks about Akka including:

"Lessons Learned: Scalable Building & Elastic Akka Clusters on Google Managed Kubernetes" by Timo Mechler and Charles Adetiloye.

"Akka Cluster vs. Kubernetes-Clustering Solutions Showdown" by Ádám Sándor and Fabio Tiriticco (one of the organizers of the very interesting https://www.meetup.com/Reactive-Amsterdam/[Reactive Amsterdam Meetup].)

"Kafka Streaming Microservices with Akka Streams and Kafka Streams" by Dean Wampler

and a much expected talk about a new trendy language : Kotlin with "Kotlin coroutines and Reactive Programming-friends or foes?" By Konrad Kamiński.

The Reactive Summit is sponsored by the world famous IBM and Disney organizations, as well as Knoldus, Red Hat, VirtusLab amongst others. Lunatech's parners will be present including Lightbend, Red Hat and Mesosphere.

Last month, https://mesosphere.com/[Mesosphere] and Lunatech Labs become partners. The Lunatech office in Rotterdam thus also hosted the first-ever https://www.meetup.com/Dutch-Mesos-User-Group/events/253207468/[Dutch Mesos User Group Meetup], whose videos can be found on our YouTube channel with https://www.youtube.com/watch?v=ua0_cO4kP8A&t=46s[this link]. This partnership reflects one of the new strategic orientations (DevOps / DC / OS / Mesos) which Lunatech has been investigating for about 1 year.

If you want to know more about the official Reactive side of the conference, the propose and a whole series of pretty well https://blog.reactivesummit.org/[written blogs] with main speakers' interviews and their motivations, follow our accounts https://twitter.com/LunatechFR[@lunatechfr] in French or https://twitter.com/LunatechLabs[@lunatechlabs] in English, as well as on https://www.linkedin.com/company/lunatech-research/[LinkedIn] and https://www.instagram.com/lunatechfr/[Instagram].
