= Snowcamp and Touraine Tech
Antoine Laffez
v1.0, 2018-01-09
:title: Snowcamp and Touraine Tech
:tags: [event]

As you know, Lunatech tries every year to participate in a large number of events in France and abroad. To meet those who "make" IT: developers, enthusiasts and students to discover new tools, trends, and learn to master them.

The first conference of the year will take place in Grenoble, a breeding ground for innovation. http://snowcamp.io/fr/[Snowcamp] will take place from January 24th to 27th organised by developers from the Grenoble Area. It was created in 2016 on the initiative of the AlpesJug bringing together volunteer and passionate geeks. 

For this 3rd edition the organisers bring us 4 days of courses, workshop and skiing session!

Wednesday, offers participants in depth and practical techniques with two sessions of 3H (Nicolas Leroux, Lunatech’s CEO will make an introduction to Scala with a live coding session). The afternoon workshops will have several topics, Docker, Kubernetes, Open Shift and Deep Learning. Notice a rather provocative workshop: "Functional Java" by Grzegorz Piwowarek;)

Conferences, on Thursday and Friday, will offer a more classic model in the form of 45-minutes presentations including functional programming, Javascript, Apache Flink, and 2 talks about micro-services.

Finally, the "unconference" on Saturday, offers speakers and participants to meet on the ski slopes of the Grenoble area.

For the first time Lunatech will sponsor this conference as a Etoile (star) Sponsor. As usual our team will welcome you with its good mood to answer all your questions about Scala and recruitment possibilities. And for sure do not forget to ask for goodies and gifts!

Tours a city located in the banks of Loire et Cher will be host the second conference of the year https://touraine.tech/[Touraine Tech]. Its first edition will be on February the 23rd. Lunatech is a Gold Sponsor on this event. The topics presented will be quite broad: UX / UI design, Backend, Cloud, Big Data, design, architecture, video games! and more. 250 people are expected for this first edition. This conference is organised by the Touraine Tech committee of the PALO ALTOURS association, made up of active members of the tech community of Tours metropole. They are also involved in volunteer training, technical workshops and digital events such as Tours JUG, GDG Tours, Web Design Workshops and Docker Tours.

This first attempt will be an opportunity to gather a wide audience of both professionals in the sector and students preparing for the professional world. They will be able to meet us at the booth. Of course, a lot of goodies, and gifts are waiting for you. With 14 conferences and 6 lightning talks the agenda promises to be excited.

Lunatech will participate in many other events as a sponsor this year such as http://devoxx.fr[Devoxx France], http://scaladays.org/[ScalaDays] Europe in Berlin and https://scala.io/[ScalaIO] Lyon amongst others. So stay tuned on Twitter https://twitter.com/LunatechFR[@LunatechFR], https://twitter.com/LunatechLabs[@LunatechLabs] or LinkedIn company page and do not forget to come and see us at the booth. It is an utmost pleasure to be part of the community and to learn from others who motivate us!
