= Friday's Internal Workshop
Antoine Laffez
v1.0, 2019-03-05
:title: Friday's Internal Workshop
:tags: [event]

Workshops are parts of our DNA. Certified trainers share their knowledge in internal workshops every Friday. Let's have a look of the schedule for ⬇️ March and April ⬇️Akka, Kafka, Cassandra and more...

**RDBMS: dive in optimization**

To build successful applications it is important to pay attention on what is happening in your database. Let's be curious: why does the database behave like that? How is data stored and accessed? How do the indexes work and are they a cure for everything? What does query planner think of our queries? How else can we improve our application performance? The goal of this workshop is to bring clarity to all that and give you some tips and ideas. Eventually, you will see that the database is your friend. We will mainly explore PostgreSQL as an example to see all this in action and play with it ourselves.

**Akka: A rehearsal in distribution**

Take your first steps in distributed programming without fear of synchronisation, network or exception handling. After this workshop you understand how to structure your actor system, avoid commons pitfall and get a full overview of the core lib from Akka.

**Spark**

From the broad spectrum that Spark offers, in this workshop we will focus on the core, understand RDDs and Datasets as the main abstractions over the distributed data, see the differences and similarities between batch and stream processing and create our own streaming application for data processing. This is an entry level workshop, showing what are the Spark capabilities, where to start from, how to create an application, how to run it (locally or in a cluster),and finally how to test it.

**Just Enough Kafka**

Every organisation creates data from its applications, how to move this data between systems is as important as the data itself.

Apache Kafka has become popular as more than a messaging system but now as a hub connecting systems in organisations.

In this workshop you will be learning about Apache Kafka’s design, configurations to consider when deploying Kafka and Kafka streaming.

**Apache Cassandra - Road from core concepts to Data modeling**

In this workshop we will start with core concepts like the CAP theorem, partitions, compaction, write path, read path, gossip protocol and more. We will end with data modelling in Cassandra, which covers keys, clustering, Chebotko diagrams, application workflow and access patterns.

After this workshop you will understand how Cassandra handles huge amounts of data and you will be equipped to model Cassandra database.

**Java 8:11 - Thou shalt not stay behind**

JDK 8 was the most breakthrough Java release in a long time, introducing not only Lambdas but very helpful constructs as Streams and Optionals. In fact it was so earth-shattering that many companies and developers are still stuck on Java 7 although so much has happened since then - 3 more releases to be precise. This workshop intends to give a catch up with the more important features from releases 8, 9, 10 and 11.

**Is your application secure?**

Our applications are mostly accessible through the Internet, meaning that anyone from around the globe can access them. So, we don’t only focus on fast implementation and optimised code, but also on how sound and secure our application is, don’t we? Nevertheless, it’s not a question of if our application will be attacked, but when. At which stage of designing and building an application should we start worrying about security? How important is security for an application and how will an adversary try to attack it? Let’s discover the answers together. To do that we are going to spend some of the time thinking and acting as attackers in order to solve some challenges. This workshops will be held in 2 parts.

If you are interested or if you want to know more, please, do not hesitate to 📩contact us ☎️ ;)
